### PR TITLE
Run validate.sh with tox.

### PR DESCRIPTION
**Pull request by rillian**
Example of setting up the test environment with tox instead, per @Callek in #26.

Two issues: travis tests verify with py26 as well, but that's hard for me. Fedora doesn't package it, and as far as I can tell, pip and tox can't install it. https://stackoverflow.com/questions/19858961/install-older-version-of-python-via-pip

I didn't update .travis.yml, but shoud.

### CODE REVIEW

**Comment by djmitche** [comment]
That's a tough one, then -- python-2.6 compatibility is required to merge, but if you don't have that version installed, there's not much you can do other than push and check the Travis results.  Not that there's anything wrong with that!

So probably the right thing to do here is to include both py26 and py27 in the tox config.  Then people in the same position as you can just try to push to Travis.

We have the 2.6 and 2.7 tests done in separate travis runs, so I don't know if it makes sense to run tox from travis.

**Comment by Callek** [comment]
I was thinking of test_tooltool being run from tox, and using -e for travis (so we can setup tox for py26 and py27), but this is an improvement I'm happy with for now anyway ;-)

**Comment by rillian** [comment]
Sorry for the churn. @Callek, is this what you had in mind?

@djmitche what do you think about only running `tox -e py27` from the Makefile?

**Comment by Callek** [comment]
I was thinking similar to the following from another project:

https://github.com/hynek/structlog/blob/master/.travis.yml

Specifically specify TOXENV and use tox -e $TOXENV as the travis command.

You can also add a toxenv for flake8/etc and run *all* the tests via tox, regardless of how they are executed.

for local you can run `tox` and while it *will* error for no py26 available, it will be known that is the issue for you, and then continue to run for py27

NOTE: I don't consider my ideal to be blocking, as 'better' is still better, if not my perfect.

p.s. thanks for the patch(es)

**Comment by rillian** [comment]
> Specifically specify TOXENV and use tox -e $TOXENV as the travis command.

That's definitely cleaner. Thanks. Doesn't look like `-e $TOXENV` is necessary; tox looks for it in the environment.

Coverage.io upload check seems to be working: https://coveralls.io/builds/4050757

**Comment by djmitche** [comment]
The point of this was to make sure that `make check` faithfully duplicates the checks performed in Travis, and that requires Python-2.6.  I don't think a Makefile that only checks Python-2.7 would be any better than what we started with.

**Comment by rillian** [comment]
Ok. I believe this is ready to merge then.

**Pull request merged**
